### ISSUE TITLE
Needs a screenshot 

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.mediaarea.BWFMetaEdit#1]
This app needs one or more screenshots added to the appdata, otherwise it looks a bit rubbish in software stores.

**Comment by nedrichards** [comment]
This has a screenshot https://github.com/flathub/net.mediaarea.BWFMetaEdit/blob/master/net.mediaarea.BWFMetaEdit.appdata.xml#L18 

I think your error is unique to Endless OS and should be reported to the Endless team directly.
