### ISSUE TITLE
libGL error

### ISSUE THREAD

**Issue by LeandroStanger** [flathub/net.mediaarea.BWFMetaEdit#2]
Gtk-Message: Failed to load module "canberra-gtk-module"
Gtk-Message: Failed to load module "canberra-gtk-module"
Qt: Session management error: None of the authentication protocols specified are supported
libpng warning: iCCP: known incorrect sRGB profile
libpng warning: iCCP: known incorrect sRGB profile
libGL error: MESA-LOADER: failed to retrieve device information
libGL error: Version 4 or later of flush extension not found
libGL error: failed to load driver: i915
libGL error: failed to open drm device: No such file or directory
libGL error: failed to load driver: i965

**Comment by LeandroStanger** [comment]
@nedrichards Could help

**Comment by g-maxime** [comment]
@nedrichards Thanks !
